name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/coverage-final.json
